# Generated by Django 4.1.1 on 2023-04-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='doc_type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='organization',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='sort',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
