# Generated by Django 4.1.1 on 2023-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_query_num_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_time',
            field=models.IntegerField(null=True),
        ),
    ]
