# Generated by Django 4.1.1 on 2023-04-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uri',
            field=models.TextField(unique=True),
        ),
    ]
