[project]
name = "parliscope-scraper"
version = "1.0.0"
description = "Scrapy spider for extracting municipal documents from SessionNet"
requires-python = ">=3.13"

dependencies = [
    "psycopg2~=2.9.10",
    "Scrapy~=2.13.3",
    "peewee~=3.18.2",
    "pytz~=2025.2",
    "Twisted~=25.5",
]
