version: '3.8'

services:
  frontend: &frontend
    image: griesheimtransparent-frontend
    container_name: griesheimtransparent-frontend
    build: "./../frontend"
    depends_on:
      - database
      - solr
      - previewservice
      - tika
      - pdfact
      - gotenberg
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - SOLR_HOST=http://solr:8983/solr
      - SOLR_COLLECTION=ris
      - RIS_DB_HOST=database
      - RIS_DB_PORT=5432
      - RIS_DB_NAME=${POSTGRES_DB}
      - RIS_DB_USER=${POSTGRES_USER}
      - RIS_DB_PASSWORD=${POSTGRES_PASSWORD}
      - DEBUG=${DEBUG}
      - UPDATE_SOLR_CRON=0 */3 * * *
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_PATH=/django_db/db.sqlite
      - DJANGO_SU_NAME=${DJANGO_SU_NAME}
      - DJANGO_SU_PASSWD=${DJANGO_SU_PASSWD}
      - DJANGO_SU_EMAIL=${DJANGO_SU_EMAIL}
      - PREVIEW_HOST=http://previewservice:8000
      - TIKA_HOST=http://tika:9998
      - PDFACT_HOST=http://pdfact:80
    volumes:
      - django_db:/django_db
      - django_staticfiles:/app/staticfiles
      - scraper_files:/filestore 
    ports:
      - 8000:8000
    command: gunicorn frontend.wsgi:application --bind 0.0.0.0:8000
    networks:
      - griesheimtransparent
    restart: no
  frontend_cron:
    <<: *frontend
    container_name: griesheimtransparent-frontend_cron
    command: cron -f
    expose: []
    restart: no
  database:
    image: postgres
    container_name: griesheimtransparent-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - griesheimtransparent
    restart: no
    volumes:
      - scraper_db:/var/lib/postgresql
  tika:
    image: apache/tika:1.28.4-full
    container_name: griesheimtransparent-tika
    ports:
      - 9995:9998
    networks:
      - griesheimtransparent
    restart: no
  scraper:
    image: griesheimtransparent-scraper
    container_name: griesheimtransparent-scraper
    build: ../scraper
    depends_on:
      - database
    environment:
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=${POSTGRES_USER}
      - DB_NAME=${POSTGRES_DB}
      - DB_HOST=database
      - DB_PORT=5432
    # command: crawl sessionnet -s SCRAPE_START=01/2023 -s SCRAPE_END 03/2023
    entrypoint: crond -f -d 0
    networks:
      - griesheimtransparent
    volumes:
      - scraper_files:/scraper/filestore
    restart: no
  solr:
    image: griesheimtransparent-solr
    container_name: griesheimtransparent-solr
    build: ../solr
    user: "8983"
    environment:
      - SOLR_LOG_LEVEL=FINEST
    ports:
      - 8983:8983
    networks:
      - griesheimtransparent
    restart: no
  previewservice:
    image: fpurchess/preview-service
    container_name: griesheimtransparent-previewservice
    ports:
      - 8000:8000
    networks:
      - griesheimtransparent
    restart: no
  pdfact:
    image: dnlbauer/pdfact-service:latest
    container_name: griesheimtransparent-pdfact
    ports:
      - 80:80
    networks:
      - griesheimtransparent
    restart: no
  gotenberg:
    image: gotenberg/gotenberg:7
    container_name: griesheimtransparent-gotenberg
    ports:
      - 3000:3000
networks:
  griesheimtransparent:
volumes:
  solr_data:
  django_db:
  django_staticfiles:
  scraper_db:
  scraper_files:

