# Generated by Django 4.1.1 on 2023-04-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_item_id', models.IntegerField()),
                ('title', models.TextField()),
                ('decision', models.TextField()),
                ('vote', models.TextField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'agendaitems',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.IntegerField()),
                ('name', models.TextField()),
                ('topic', models.TextField()),
                ('type', models.TextField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'consultations',
            },
        ),
        migrations.CreateModel(
            name='ConsultationMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ris.consultation')),
            ],
            options={
                'db_table': 'consultation_meeting',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField()),
                ('file_name', models.TextField()),
                ('content_type', models.TextField()),
                ('content_binary', models.BinaryField()),
                ('size', models.IntegerField()),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ris.document')),
            ],
            options={
                'db_table': 'document_meeting',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField()),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.IntegerField()),
                ('title', models.TextField()),
                ('title_short', models.TextField()),
                ('date', models.DateTimeField()),
                ('consultations', models.ManyToManyField(related_name='meeting_id', through='ris.ConsultationMeeting', to='ris.consultation')),
                ('documents', models.ManyToManyField(related_name='meeting_id', through='ris.DocumentMeeting', to='ris.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='meetings', to='ris.organization')),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
        migrations.AddField(
            model_name='documentmeeting',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ris.meeting'),
        ),
        migrations.CreateModel(
            name='DocumentConsulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ris.consultation')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ris.document')),
            ],
            options={
                'db_table': 'document_consultation',
            },
        ),
        migrations.CreateModel(
            name='DocumentAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ris.agendaitem')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ris.document')),
            ],
            options={
                'db_table': 'document_agenda_item',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='agenda_items',
            field=models.ManyToManyField(related_name='document_id', through='ris.DocumentAgendaItem', to='ris.agendaitem'),
        ),
        migrations.AddField(
            model_name='document',
            name='consultations',
            field=models.ManyToManyField(related_name='document_id', through='ris.DocumentConsulation', to='ris.consultation'),
        ),
        migrations.AddField(
            model_name='document',
            name='meetings',
            field=models.ManyToManyField(related_name='document_id', through='ris.DocumentMeeting', to='ris.meeting'),
        ),
        migrations.AddField(
            model_name='consultationmeeting',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ris.meeting'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='meetings',
            field=models.ManyToManyField(related_name='consultation_id', through='ris.ConsultationMeeting', to='ris.meeting'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agenda_items', to='ris.consultation'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='documents',
            field=models.ManyToManyField(related_name='agenda_item_id', through='ris.DocumentAgendaItem', to='ris.document'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agenda_items', to='ris.meeting'),
        ),
    ]
