# Generated by Django 4.1.1 on 2023-04-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
