# Generated by Django 4.1.1 on 2023-04-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ris', '0002_alter_document_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
