# Generated by Django 4.2.1 on 2023-06-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ris', '0004_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
