database_url: "sqlite:///:memory:"

# site-specific
base_url: https://sessionnet.krz.de/griesheim/bi/
mandate_holder_url_suffix: kp0041.asp
organizations_url_suffix: gr0040.asp
organizations_details_url_suffix: kp0040.asp
calendar_url_suffix: si0040.asp
meeting_url_link_suffix: si0057.asp
meeting_url_overview_suffix: si0050.asp
meeting_url_agenda_suffix: si0057.asp
agenda_url_link_suffix: to0050.asp
consultation_url_link_suffix: vo0050.asp
consultation_new_link_suffix: vo0040.asp
meeting_document_link_suffix: getfile.asp

xml_selectors:
  mandate_row: "//tbody/tr/td"
  organizations_row: "//tbody/tr/td"
  organizations_mandate_name: "//tbody/tr/td[contains(@data-label, 'Name')]"
  meeting_link: "//table[contains(@class, 'table-striped')]/tbody/tr/td/div/a/@href"
  meeting_information_table: "//div[contains(@class, 'smc_page_si0050_contenttable')]//div[contains(@class, 'smc-table-cell')]"
  document_link: "//a/@href"
  meeting_agenda_link: "//tr[contains(@class, 'smc-t-r-l')]//a[contains(@class, 'smc_datatype_t')]/@href"
  agenda_item_decision: "//p[contains(@class, 'smc_field_btname')]"
  agenda_item_vote: "//p[contains(@class, 'smc_field_toabst')]"
  agenda_item_text: "//div[contains(@class, 'WordSection1')]"
  consultation_name: "//div[contains(@class, 'voname')]"
  consultation_type: "//div[contains(@class, 'vovaname')]"
  consultation_text: "//div[contains(@class, 'WordSection1')]"
