"""
Django settings for parliscope project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from os.path import join
from pathlib import Path

import environ

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG:
    SECRET_KEY = "my-debug-secret-key"
else:
    SECRET_KEY = env("SECRET_KEY")

# share referrer
SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"

ALLOWED_HOSTS = [
    host for host in env("ALLOWED_HOSTS", default="").split(",") if len(host) > 0
]
CSRF_TRUSTED_ORIGINS = [
    f"http://{host}"
    for host in env("ALLOWED_HOSTS", default="").split(",")
    if len(host) > 0
]
CSRF_TRUSTED_ORIGINS += [
    f"https://{host}"
    for host in env("ALLOWED_HOSTS", default="").split(",")
    if len(host) > 0
]

# Application definition
INSTALLED_APPS = [
    "parliscope",
    "frontend",
    "models",
    "healthcheck",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "fontawesomefree",
    "health_check",
    "health_check.db",
    "health_check.contrib.migrations",
    "django_celery_results",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = "parliscope.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "parliscope.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "HOST": env("DB_HOST", default="localhost"),
        "PORT": env("DB_PORT", default="5432"),
        "NAME": env("DB_NAME", default="riscraper"),
        "USER": env("DB_USER", default="riscraper"),
        "PASSWORD": env("DB_PASSWORD", default="riscraper"),
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGE_CODE = "de-de"

TIME_ZONE = "Europe/Berlin"
USE_TZ = True

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# document file storage base directory
DOCUMENT_STORE = env("DOCUMENT_STORE", default="/filestore")
CACHE_DIR = join(DOCUMENT_STORE, "analysis")

# Connection to solr
SOLR_HOST = env("SOLR_HOST", default="http://localhost:8983/solr")
SOLR_COLLECTION = env("SOLR_COLLECTION", default="ris")

# Connection and settings for pdf preview thumbnails
PREVIEW_HOST = env("PREVIEW_HOST", default="http://localhost:8000")
PREVIEW_RESOLUTION = "256x256"

TIKA_HOST = env("TIKA_HOST", default="http://localhost:9998")
PDFACT_HOST = env("PDFACT_HOST", default="http://localhost:80")
GOTENBERG_HOST = env("GOTENBERG_HOST", default="http://localhost:3000")

CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = "django-db"  # use django_celery_results
CELERY_TASK_STORE_ERRORS_EVEN_IF_IGNORED = True  # store all task errors
CELERY_TASK_TRACK_STARTED = True  # track when task was started
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 14  # task results expire after 14 days
CELERY_RESULT_EXTENDED = True  # store more info about task results
CELERY_BEAT_SCHEDULER = (
    "django_celery_beat.schedulers:DatabaseScheduler"  # use database for periodic tasks
)
