# Generated by Django 4.1.1 on 2023-04-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_query_doc_type_query_organization_query_sort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='page',
            field=models.IntegerField(null=True),
        ),
    ]
