# Generated by Django 4.1.1 on 2023-04-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('topic', models.TextField()),
                ('type', models.TextField()),
                ('text', models.TextField(null=True)),
            ],
            options={
                'db_table': 'consultations',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_id', models.IntegerField(unique=True)),
                ('file_name', models.TextField(null=True)),
                ('uri', models.TextField()),
                ('content_type', models.TextField(null=True)),
                ('size', models.IntegerField()),
                ('title', models.TextField(null=True)),
                ('checksum', models.TextField()),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_id', models.IntegerField(null=True)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'persons',
                'unique_together': {('name', 'person_id')},
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_id', models.IntegerField(unique=True)),
                ('title', models.TextField()),
                ('title_short', models.TextField()),
                ('date', models.DateTimeField()),
                ('consultations', models.ManyToManyField(db_constraint=False, to='ris.consultation')),
                ('documents', models.ManyToManyField(db_constraint=False, to='ris.document')),
                ('organization', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ris.organization')),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='documents',
            field=models.ManyToManyField(to='ris.document'),
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agenda_item_id', models.IntegerField(unique=True)),
                ('title', models.TextField()),
                ('decision', models.TextField(null=True)),
                ('vote', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('consultation', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ris.consultation')),
                ('documents', models.ManyToManyField(to='ris.document')),
                ('meeting', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ris.meeting')),
            ],
            options={
                'db_table': 'agendaitems',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='ris.organization')),
                ('person', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='ris.person')),
            ],
            options={
                'db_table': 'memberships',
                'unique_together': {('person_id', 'organization_id')},
            },
        ),
    ]
