"""
Django settings for frontend project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from os.path import join
from pathlib import Path
import environ

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default="django-insecure-$vob9+fgpc=h_2e57lc=3*vsae(x0-jd@cexqzhdqaoa29qcy4")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

# share referrer
SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"


ALLOWED_HOSTS = [host for host in env("ALLOWED_HOSTS", default="").split(",") if len(host) > 0]
CSRF_TRUSTED_ORIGINS = [f"http://{host}" for host in env("ALLOWED_HOSTS", default="").split(",") if len(host) > 0]
CSRF_TRUSTED_ORIGINS += [f"https://{host}" for host in env("ALLOWED_HOSTS", default="").split(",") if len(host) > 0]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "frontend",
    "ris",
    "fontawesomefree",
    "django_crontab",
    "health_check",
    "health_check.db",
    'health_check.contrib.migrations',
]

CRONJOBS = [
    (env("UPDATE_SOLR_CRON", default="0 */3 * * *"), "django.core.management.call_command", ["update_solr"])
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "frontend.middleware.RestrictUserMiddleware"
]


ROOT_URLCONF = "frontend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "frontend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": env("DATABASE_PATH", default=BASE_DIR / "db.sqlite3"),
    },
    "ris": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "HOST": env("RIS_DB_HOST"),
        "PORT": env("RIS_DB_PORT"),
        "NAME": env("RIS_DB_NAME"),
        "USER": env("RIS_DB_USER"),
        "PASSWORD": env("RIS_DB_PASSWORD")
    }
}
DATABASE_ROUTERS = ['frontend.databaserouter.DatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "de-de"

TIME_ZONE = "Europe/Berlin"
USE_TZ = True

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# document file storage base directory
DOCUMENT_STORE = env("DOCUMENT_STORE", default="/filestore")

# Connection to solr
SOLR_HOST = env("SOLR_HOST", default="http://localhost:8983/solr")
SOLR_COLLECTION = env('SOLR_COLLECTION', default="ris")

# Connection and settings for pdf preview thumbnails
PREVIEW_HOST = env("PREVIEW_HOST", default="http://localhost:9997")
PREVIEW_RESOLUTION = "256x256"

TIKA_HOST = env("TIKA_HOST", default="http://localhost:9998")
PDFACT_HOST = env("PDFACT_HOST", default="http://localhost:9997")
