name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: dnlbauer
  IMAGE_BASE_NAME: dnlbauer/griesheimtransparent

jobs:
  build_solr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Extract metadata for container tagging
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{env.CONTAINER_REGISTRY }}/${{ env.IMAGE_BASE_NAME }}-solr
    - name: Login to container registry
      uses: docker/login-action@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ env.CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: "./solr"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outpyts.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Extract metadata for container tagging
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{env.CONTAINER_REGISTRY }}/${{ env.IMAGE_BASE_NAME }}-frontend
    - name: Login to container registry
      uses: docker/login-action@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ env.CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: "./frontend"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outpyts.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
  build_scraper:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Extract metadata for container tagging
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{env.CONTAINER_REGISTRY }}/${{ env.IMAGE_BASE_NAME }}-scraper
    - name: Login to container registry
      uses: docker/login-action@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ env.CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: "./scraper"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outpyts.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

       
